spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/lifeonair
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    
  jpa:
    database: mariadb
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.globally_quoted_identifiers: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
          kakao:
            client-id: 25b1cd661cef6893ef871ce1b8124441
            client-secret: C7YZb3Z1jYZJLtNkTmWYQNba9zurqCM6
            redirect-uri: "http://localhost:8081/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
server:
  frontEnd: ${FRONT_END}
  backEnd: http://localhost:8081
  port: 8081
