spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/lifeonair
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.globally_quoted_identifiers: true
        
server:
  port: 8081
